### ISSUE TITLE
click function call throws Uncaught object "[object Object]" was thrown. Throw Error instead.

### ISSUE THREAD

**Issue by vmasalau** [DevExpress/testcafe-browser-provider-phantomjs#7]
I am facing this error when I try to use click function.

The code:
```
const btn = await Selector('.button[name="login"]');
await t
 .expect(btn.exists).ok() 
 .click(btn);
```

Exception:
Uncaught object "[object Object]" was thrown. Throw Error instead.

if I run it with chrome, works fine.
If I remove click, works fine.

So, I suppose it's an issue with the provider. Could you give me a clue, what could be wrong.

**Comment by AndreyBelym** [comment]
Hello @vmasalau! `phantomjs` uses an outdated version of WebKit, that can be a reason of your problem. Can you give me a link to the test page or the test page sources, please?

**Comment by AndreyBelym** [comment]
Also, due to numerous issues in PhantomJS, it's highly recommended to use https://www.npmjs.com/package/testcafe-browser-provider-nightmare

**Comment by AndreyBelym** [comment]
I close this issue due to the project is discontinued for about 2 years. If you still use this provider, please consider using alternatives like [Chrome Headless](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.html) and https://www.npmjs.com/package/testcafe-browser-provider-nightmare.
